//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acropolis_Museum.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acropolis_Museum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10 {
            get {
                object obj = ResourceManager.GetObject("10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123 {
            get {
                object obj = ResourceManager.GetObject("123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8 {
            get {
                object obj = ResourceManager.GetObject("8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9 {
            get {
                object obj = ResourceManager.GetObject("9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap akropoli {
            get {
                object obj = ResourceManager.GetObject("akropoli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico1 {
            get {
                object obj = ResourceManager.GetObject("ico1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico2 {
            get {
                object obj = ResourceManager.GetObject("ico2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img3 {
            get {
                object obj = ResourceManager.GetObject("img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img4 {
            get {
                object obj = ResourceManager.GetObject("img4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img5 {
            get {
                object obj = ResourceManager.GetObject("img5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img6 {
            get {
                object obj = ResourceManager.GetObject("img6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img7 {
            get {
                object obj = ResourceManager.GetObject("img7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img8 {
            get {
                object obj = ResourceManager.GetObject("img8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_room1 {
            get {
                object obj = ResourceManager.GetObject("map_room1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_room2 {
            get {
                object obj = ResourceManager.GetObject("map_room2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_room3 {
            get {
                object obj = ResourceManager.GetObject("map_room3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_room4 {
            get {
                object obj = ResourceManager.GetObject("map_room4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_room5 {
            get {
                object obj = ResourceManager.GetObject("map_room5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map2 {
            get {
                object obj = ResourceManager.GetObject("map2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mystery {
            get {
                object obj = ResourceManager.GetObject("mystery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Λουτροφόρος
        /// 
        ///
        ///Δημιουργός: Εργαστήριο αττικό
        ///Είδος: Αγγείο
        ///Εποχή: Αρχαϊκή εποχή
        ///Χρονολόγηση: Γύρω στο 525 π.Χ.
        ///Υλικό:Πηλός
        ///
        ///.
        /// </summary>
        internal static string object1 {
            get {
                return ResourceManager.GetString("object1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Άγαλμα Παπποσιληνού με μικρό Διόνυσο
        ///
        ///
        ///Είδος: Έργο πλαστικής
        ///Εποχή: Ελληνιστική εποχή
        ///Χρονολόγηση: 2ος αι. π.Χ.
        ///Υλικό: Μάρμαρο Πάρου.
        /// </summary>
        internal static string object2 {
            get {
                return ResourceManager.GetString("object2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Άγαλμα Νίκης
        ///
        ///
        ///Είδος: Έργο κοροπλαστικής
        ///Εποχή: Ρωμαϊκή εποχή
        ///Χρονολόγηση: 1ος-2ος αι. μ.Χ.
        ///Υλικό: Πηλός.
        /// </summary>
        internal static string object3 {
            get {
                return ResourceManager.GetString("object3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πεσσός με τάμα στον Ασκληπιό. Το «Ανάθημα του Πραξία»
        ///
        ///Είδος: Έργο πλαστικής
        ///Εποχή: Κλασική εποχή
        ///Χρονολόγηση: 350-300 π.Χ.
        ///Υλικό: Μάρμαρο Πάρου.
        /// </summary>
        internal static string object4 {
            get {
                return ResourceManager.GetString("object4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πύραυνο
        ///
        ///
        ///Είδος: Οικιακός εξοπλισμός
        ///Εποχή: Ελληνιστική εποχή
        ///Χρονολόγηση: 150-86 π.Χ.
        ///Υλικό:Πηλός.
        /// </summary>
        internal static string object5 {
            get {
                return ResourceManager.GetString("object5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_room3_1 {
            get {
                object obj = ResourceManager.GetObject("pic_room3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_room3_2 {
            get {
                object obj = ResourceManager.GetObject("pic_room3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_room3_3 {
            get {
                object obj = ResourceManager.GetObject("pic_room3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_room4_1 {
            get {
                object obj = ResourceManager.GetObject("pic_room4_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_room4_2 {
            get {
                object obj = ResourceManager.GetObject("pic_room4_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pic_room4_3 {
            get {
                object obj = ResourceManager.GetObject("pic_room4_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο πρώτος εκθεσιακός χώρος, στο ισόγειο του Μουσείου, περιλαμβάνει ευρήματα από τις κλιτύς της Ακρόπολης. Η περιοχή, αδιάσπαστο τμήμα της τοπογραφίας και της ιστορίας του βράχου, φιλοξενεί μικρά και μεγάλα ιερά, παλαιές και νεότερες λατρείες, χώρους θεαμάτων και, λίγο χαμηλότερα, κατοικίες ιδιωτών.
        ///
        ///Το επικλινές δάπεδο της αίθουσας παραπέμπει στη διαδρομή που ακολουθεί ο επισκέπτης της αρχαιότητας καθώς ανηφορίζει στον βράχο της Ακρόπολης, ενώ οι διαφανείς γυάλινες θυρίδες προσφέρουν στον σημερινό επισκέπτ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room1 {
            get {
                return ResourceManager.GetString("room1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room1_background {
            get {
                object obj = ResourceManager.GetObject("room1_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream room1_sound {
            get {
                return ResourceManager.GetStream("room1_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στα αριστερά της μεγάλης κλίμακας που οδηγεί από το ισόγειο στον πρώτο όροφο παρουσιάζονται ευρήματα συνδεδεμένα με το απώτερο παρελθόν της Ακρόπολης. Είναι αντικείμενα που σηματοδοτούν την εξέλιξη του βράχου από οχυρό και έδρα του τοπικού ηγεμόνα σε τόπο ιερό, αφιερωμένο στη λατρεία της Αθηνάς και άλλων θεών.
        /// </summary>
        internal static string room2 {
            get {
                return ResourceManager.GetString("room2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σε τέσσερις συνεχόμενες προθήκες παρουσιάζονται ευρήματα από την Ακρόπολη της Μυκηναϊκής εποχής. Τον 13ο αι. π.Χ. η Ακρόπολη, οχυρωμένη με ισχυρά τείχη, αποτελεί την έδρα του τοπικού ηγεμόνα και τον τόπο κατοικίας της άρχουσας τάξης. Ο βασιλιάς ασκεί πολιτική και θρησκευτική εξουσία στις διάσπαρτες κοινότητες της Αττικής, που σύμφωνα με την αρχαία παράδοση, έχουν τώρα συνενωθεί διοικητικά, έχουν κοινούς θεούς, κοινό λατρευτικό κέντρο στην Ακρόπολη και κοινή γιορτή, τα Παναθήναια, προς τιμή της πολιούχου θεά [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room2_1 {
            get {
                return ResourceManager.GetString("room2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_1_1 {
            get {
                object obj = ResourceManager.GetObject("room2_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφυρί
        ///
        ///Βρέθηκε το 1888 στα ανατολικά του Παρθενώνα και αποτελεί μέρος του λεγόμενου «θησαυρού του χαλκουργού». Η μια άκρη του καταλήγει σε επίπεδη επιφάνεια, η άλλη σε πεπλατυσμένη αιχμή ενώ στη μέση διαμορφώνεται ελλειψοειδής οπή για την ένθεση της ξύλινης λαβής. Οι σφύρες (σφυριά) αποτελούν συνηθισμένα εργαλεία χαλκουργών, ξυλουργών και γενικότερα τεχνιτών..
        /// </summary>
        internal static string room2_1_1_text {
            get {
                return ResourceManager.GetString("room2_1_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_1_2 {
            get {
                object obj = ResourceManager.GetObject("room2_1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αμφορέας
        ///
        ///Αμφορέας, συγκολλημένος από πολλά θραύσματα και συμπληρωμένος. Βρέθηκε το 1937-1938 στην ανασκαφή της «μυκηναϊκής κρήνης» στη βόρεια κλιτύ (πλαγιά) της Ακρόπολης.
        ///
        ///Έχει δισκόμορφη βάση, σφαιρικό σώμα, κυλινδρικό λαιμό, χείλος στραμμένο προς τα έξω και κάθετες λαβές. Είναι διακοσμημένος με καστανόμαυρες οριζόντιες και κάθετες ταινίες. Πιθανότατα, χρησίμευε στην άντληση νερού από την πηγή και στη μεταφορά του..
        /// </summary>
        internal static string room2_1_2_text {
            get {
                return ResourceManager.GetString("room2_1_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_1_3 {
            get {
                object obj = ResourceManager.GetObject("room2_1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αλάβαστρο
        ///
        ///Σχεδόν ακέραιο αλάβαστρο. Βρέθηκε πιθανότατα το 1873-1874 ανατολικά του Παρθενώνα. Έχει στρογγυλεμένη βάση, σφαιρικό σώμα, ψηλό χείλος και τρεις όρθιες λαβές που κολλούν στα τοιχώματα, η μία σπασμένη. Το αγγείο είναι διακοσμημένο με κυματιστές γραμμές καστανοκόκκινου χρώματος..
        /// </summary>
        internal static string room2_1_3_text {
            get {
                return ResourceManager.GetString("room2_1_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_1_4 {
            get {
                object obj = ResourceManager.GetObject("room2_1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κεφάλι ειδωλίου
        ///
        ///Κεφάλι ειδωλίου, ίσως Σφίγγας. Βρέθηκε το 1969 στην περιοχή του ιερού του Απόλλωνα υπ’ Άκραις, στη βόρεια πλαγιά της Ακρόπολης.
        ///
        ///Διατηρείται μόνο το πρόσωπο, το οποίο στο πίσω μέρος είναι κοίλο. Το σχήμα του είναι τριγωνικό, το μέτωπο χαμηλό, τα μάτια λοξά, τα φρύδια τονισμένα, η μύτη μεγάλη και μακριά και το στόμα στενό και μισάνοιχτο. Το πηγούνι είναι τριγωνικό, ιδιαίτερα μακρύ, και ίσως απολήγει σε γένι. Ολόκληρη η επιφάνεια του προσώπου καλύπτεται με κιτρινωπό επίχρισμα και τα χαρακ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room2_1_4_text {
            get {
                return ResourceManager.GetString("room2_1_4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_1_5 {
            get {
                object obj = ResourceManager.GetObject("room2_1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σφραγιδόλιθος
        ///
        ///Σφραγιδόλιθος, σπασμένος στην περιφέρεια. Βρέθηκε στην Ακρόπολη. Στη σφραγιστική επιφάνεια αποδίδονται τέσσερις κύκλοι με βάθυνση στο εσωτερικό τους. Διακρίνεται η διαμπερής οπή, από την οποία περνούσε το κορδόνι για την ανάρτηση του σφραγιδόλιθου. Η πίσω όψη είναι ακόσμητη..
        /// </summary>
        internal static string room2_1_5_text {
            get {
                return ResourceManager.GetString("room2_1_5_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_1_6 {
            get {
                object obj = ResourceManager.GetObject("room2_1_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πέλεκυς
        ///
        ///Διπλός ή αμφίστομος πέλεκυς (τσεκούρι). Βρέθηκε το 1888 στα ανατολικά του Παρθενώνα και αποτελεί μέρος του λεγόμενου «θησαυρού του χαλκουργού». Στα δύο άκρα απολήγει σε κόψεις-λεπίδες ενώ στη μέση έχει μια ελλειψοειδή οπή στειλέωσης, για την ένθεση της ξύλινης λαβής. Στις ακμές των κόψεων διακρίνονται φθορές, που ίσως οφείλονται στη χρήση του αντικειμένου. Οι διπλοί πελέκεις χρησιμοποιούνταν ως εργαλεία κοπής στην υλοτομία και ως επιθετικά όπλα στο κυνήγι..
        /// </summary>
        internal static string room2_1_6_text {
            get {
                return ResourceManager.GetString("room2_1_6_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream room2_1_sound {
            get {
                return ResourceManager.GetStream("room2_1_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το χάλκινο έλασμα με την παράσταση της μυθικής Γοργούς, που παρουσιάζεται σε ξεχωριστή προθήκη, σηματοδοτεί τον μετασχηματισμό της Ακρόπολης από ανακτορικό κέντρο σε ιερό. 
        ///
        ///Μέχρι τα τέλη του 8ου αι. π.Χ. ο θεσμός της κληρονομικής βασιλείας έχει αποδυναμωθεί και η εξουσία έχει μεταβιβαστεί σε μια μικρή ομάδα αριστοκρατών. Οι νέοι άρχοντες μεταφέρουν το διοικητικό κέντρο στη βορειοανατολική πλαγιά του βράχου, και έτσι η κορυφή της Ακρόπολης μετατρέπεται σε τόπο λατρείας των θεών. Τον 8ο και τον 7ο αι. π.Χ. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room2_2 {
            get {
                return ResourceManager.GetString("room2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_2_1 {
            get {
                object obj = ResourceManager.GetObject("room2_2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_2_2 {
            get {
                object obj = ResourceManager.GetObject("room2_2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room2_2_3 {
            get {
                object obj = ResourceManager.GetObject("room2_2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream room2_sound {
            get {
                return ResourceManager.GetStream("room2_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αίθουσα χωρίζεται σε 2 θεματικές ενότητες.Για περισσότερες πληροφορίες επέλεξε την αντίστοιχη θεματική ενότητα που σε ενδιαφέρει και κάνε κλικ στο κουμπί &quot;Υποβολή&quot;.
        /// </summary>
        internal static string room2_θεμ_εν {
            get {
                return ResourceManager.GetString("room2_θεμ_εν", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το ανατολικό και νότιο τμήμα του πρώτου ορόφου είναι αφιερωμένο στην Ακρόπολη της Αρχαϊκής εποχής (700-480 π.Χ.). Μια Ακρόπολη διαφορετική από αυτή των κλασικών χρόνων που γνωρίζουμε σήμερα, αλλά εξίσου μεγαλοπρεπή, με εντυπωσιακούς ναούς και πολυάριθμα αφιερώματα. 
        ///
        ///Το φυσικό φως που εισέρχεται από τα μεγάλα υαλοστάσια και τους φεγγίτες της οροφής δημιουργεί την αίσθηση του υπαίθριου χώρου και παραπέμπει στους εξωτερικούς χώρους του ιερού της Ακρόπολης, όπου ήταν στημένα τα γλυπτά στην αρχαιότητα..
        /// </summary>
        internal static string room3 {
            get {
                return ResourceManager.GetString("room3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_1_1 {
            get {
                object obj = ResourceManager.GetObject("room3_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έχει αποκατασταθεί από θραύσματα, που βρέθηκαν το 1882 νοτιοανατολικά του Παρθενώνα. Πιθανότατα κοσμούσε ένα από τα οικήματα της αρχαϊκής Ακρόπολης.
        ///Θέμα του αετώματος είναι ένας από τους άθλους του Ηρακλή, η πάλη του με τη Λερναία Ύδρα. Το μυθικό τέρας, από το σώμα του οποίου φυτρώνουν εννέα φίδια με υψωμένα κεφάλια, καταλαμβάνει το δεξί τμήμα του αετώματος. Στα αριστερά του ο Ηρακλής, φορώντας θώρακα και έχοντας κρεμασμένο στον δεξί του ώμο τον τελαμώνα, προσπαθεί να το καταβάλει με το ρόπαλο που κρατά σ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_1_1_text {
            get {
                return ResourceManager.GetString("room3_1_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_1_2 {
            get {
                object obj = ResourceManager.GetObject("room3_1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποσπασματικά σωζόμενη πλάκα με παράσταση ηνίοχου. Βρέθηκε το 1859 κοντά στα Προπύλαια και έχει συμπληρωθεί.
        ///
        ///Ο ηνίοχος ετοιμάζεται να ανέβει στο τέθριππο πατώντας ήδη το αριστερό πόδι πάνω στον δίφρο του άρματος. Φορά μακρύ χιτώνα και ιμάτιο που πέφτει στους ώμους. Τα μαλλιά του αναδιπλώνονται στον αυχένα και δένονται σε κότσο περνώντας μέσα από ταινία. Τα χέρια του είναι τεντωμένα μπροστά και κρατούν τα ηνία των αλόγων. Από τα άλογα έχουν σκαλιστεί σε αυτόν τον λίθο οι ουρές και τα πίσω σκέλη, ενώ τα υπ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_1_2_text {
            get {
                return ResourceManager.GetString("room3_1_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_1_3 {
            get {
                object obj = ResourceManager.GetObject("room3_1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Σύμπλεγμα που αποδίδεται στη διακόσμηση του ενός από τα δύο αετώματα του Εκατόμπεδου, πιθανότατα του ανατολικού. Βρέθηκε σε θραύσματα το 1888 στα ανατολικά και τα νοτιανατολικά του Παρθενώνα και είναι συμπληρωμένο σε μεγάλο βαθμό.
        ///
        ///Το σύμπλεγμα εικονίζει λέαινα να κατασπαράζει μοσχαράκι, θέμα ιδιαίτερα αγαπητό στη διακόσμηση των πρώιμων αρχαϊκών ναών με καταβολές από την τέχνη της Εγγύς Ανατολής. Η ασυνήθιστη λέαινα, συνδυάζει θηλυκά και αρσενικά χαρακτηριστικά, δηλαδή μαστούς και πλούσια χαίτη..
        /// </summary>
        internal static string room3_1_3_text {
            get {
                return ResourceManager.GetString("room3_1_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_1_4 {
            get {
                object obj = ResourceManager.GetObject("room3_1_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήμα θριγκού από τη γωνία ενός από τα μικρότερα αρχαϊκά οικοδομήματα της Ακρόπολης. Σώζεται αποσπασματικά. Αποτελείται από πώρινα μέλη όπως το επιστύλιο, τα τρίγλυφα, τις μετόπες, το γείσο καθώς και τη μαρμάρινη σίμη.
        ///Το τμήμα του επιστυλίου που σώζεται φέρει επιμήκη ταινία στην άνω απόληξή του καθώς και μικρούς κανόνες. Κάθε κανόνας διακοσμείται με έξι κυλινδρικές σταγόνες, που αποδίδουν πιθανόν τα καρφιά. Τα τρίγλυφα εναλλάσσονται με τις, άλλοτε διακοσμημένες με ανάγλυφες ή γραπτές παραστάσεις, μετόπες. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_1_4_text {
            get {
                return ResourceManager.GetString("room3_1_4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_1_5 {
            get {
                object obj = ResourceManager.GetObject("room3_1_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τμήμα σίμης από τη δεξιά γωνία της στέγης του λεγόμενου «Αρχαίου Ναού». Η οριζόντια πλευρά απολήγει σε λεοντοκεφαλή με πλούσιες ανάγλυφες λεπτομέρειες τονισμένες με χρώματα: μπλε για τη χαίτη, κίτρινο για τα αυτιά, καστανό για τις ίριδες και τις κόρες των ματιών και κόκκινο για το στόμα, από το οποίο έρρεε το νερό της βροχής. Στα αριστερά σώζεται μέρος ζωγραφιστού ανθεμίου με μπλε πέταλα. Το επικλινές μέτωπο της σίμης, που βρισκόταν πάνω από το αέτωμα, ήταν διακοσμημένο με σχέδιο ανθεμίων, ελίκων και ανθέων [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_1_5_text {
            get {
                return ResourceManager.GetString("room3_1_5_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_1_6 {
            get {
                object obj = ResourceManager.GetObject("room3_1_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ακροκέραμο με ανάγλυφο γοργόνειο το οποίο έχει συγκολληθεί από δύο θραύσματα. Βρέθηκε το 1835 νοτιοδυτικά του Παρθενώνα.
        ///
        ///Στο πρόσωπο της Μέδουσας κυριαρχούν τα μεγάλα μάτια, το ρυτιδιασμένο μέτωπο και το πλατύ στόμα από το οποίο προεξέχουν οι χαυλιόδοντες και η γλώσσα. Τα αποτροπαϊκά χαρακτηριστικά τονίζονταν με χρώματα από τα οποία διακρίνονται ίχνη μαύρου και κόκκινου. Στα αυτιά φορά κυκλικά σκουλαρίκια και στον λαιμό τυλίγονται φίδια..
        /// </summary>
        internal static string room3_1_6_text {
            get {
                return ResourceManager.GetString("room3_1_6_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο πρώτος μνημειακός ναός της Ακρόπολης ιδρύεται στη θέση του μικρού πλινθόκτιστου ναού της Αθηνάς Παρθένου. Οι αρχαιολόγοι τον ονομάζουν «αρχαϊκό Παρθενώνα» και πιθανότατα πρόκειται για τον Εκατόμπεδο που αναφέρουν οι αρχαίες πηγές. Πότε ακριβώς κατασκευάζεται δεν είναι γνωστό, πολλοί ωστόσο συνδέουν την οικοδόμησή του με την καθιέρωση της γιορτής των Μεγάλων Παναθηναίων, το 566/5 π.Χ. Παρότι τα θεμέλια του Εκατομπέδου έχουν εξαφανιστεί, την ύπαρξή του μαρτυρούν τα μεγάλα γλυπτά και τα αρχιτεκτονικά μέλη πο [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_1_text {
            get {
                return ResourceManager.GetString("room3_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_2_1 {
            get {
                object obj = ResourceManager.GetObject("room3_2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ίνακας διακοσμημένος με τη μελανόμορφη τεχνική από τις ανασκαφές της Ακρόπολης. Λείπει τμήμα από τη δεξιά πλευρά.
        ///
        ///Μία γυναίκα καθισμένη σε δίφρο (σκαμνί), ασχολείται με κάποια οικιακή εργασία πάνω στο τραπέζι που έχει μπροστά της. Ίσως υφαίνει σε μικρό φορητό αργαλειό ή ζυμώνει. Φορά πλούσια διακοσμημένο πέπλο και κόκκινη ταινία στα μαλλιά. Πίσω της ένα γυμνό κορίτσι παίζει καθισμένο στο πάτωμα. Το εσωτερικό της οικίας δηλώνεται από τα έπιπλα και τα αντικείμενα που είναι τοποθετημένα σε ράφι ή κρεμασμένα [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_2_1_text {
            get {
                return ResourceManager.GetString("room3_2_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_2_2 {
            get {
                object obj = ResourceManager.GetObject("room3_2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ειδώλιο Αθηνάς από τις ανασκαφές της Ακρόπολης. Η θεά φορά μακρύ χιτώνα με μανίκια και από πάνω ιμάτιο περασμένο λοξά κάτω από την αριστερή μασχάλη. Τα χέρια της είναι λυγισμένα με το αριστερό κοντά στον κορμό και το δεξί προτεταμένο. Το πρόσωπό της είναι τετράγωνο, με μεγάλα αμυγδαλόσχημα μάτια. Στο κεφάλι φοράει κράνος κάτω από το οποίο τα μαλλιά πέφτουν σε τρεις πλεξούδες στον δεξιό ώμο. Στην επιφάνεια του ειδωλίου διατηρούνται ίχνη λευκού επιχρίσματος..
        /// </summary>
        internal static string room3_2_2_text {
            get {
                return ResourceManager.GetString("room3_2_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_2_3 {
            get {
                object obj = ResourceManager.GetObject("room3_2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Αποσπασματικά σωζόμενο αναθηματικό ανάγλυφο με παράσταση κεραμέα. Βρέθηκε το 1887 ανατολικά του Ερεχθείου, συγκολλήθηκε και συμπληρώθηκε.
        ///
        ///Ο άνδρας κάθεται σε δίφρο (σκαμνί) φορώντας ιμάτιο που αφήνει γυμνό το επάνω μέρος του σώματός του. Πρόκειται για αγγειοπλάστη που κρατά στο αριστερό χέρι δύο από τις κύλικες που έφτιαξε για να τις αφιερώσει στην Αθηνά Εργάνη. Ίχνη μπλε, κόκκινου και κίτρινου χρώματος διακρίνονται στο κάθισμα, το ιμάτιο και στο πρόσωπο της μορφής καθώς και στο βάθος του αναγλύφου..
        /// </summary>
        internal static string room3_2_3_text {
            get {
                return ResourceManager.GetString("room3_2_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_2_4 {
            get {
                object obj = ResourceManager.GetObject("room3_2_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Πινάκιο (πιάτο) διακοσμημένο με τη μελανόμορφη τεχνική. Έχει συγκολληθεί από θραύσματα και συμπληρωθεί.
        ///
        ///Στον πυθμένα του αγγείου εικονίζεται η πάλη του Θησέα με τον Μινώταυρο, την οποία παρακολουθεί η Αριάδνη. Ο Θησέας φορά περίζωμα που καλύπτει τους μηρούς του και στεφάνι στο κεφάλι. Καρφώνει με το ξίφος του το τέρας στον λαιμό, από όπου αναβλύζει αίμα. Ο Μινώταυρος, ο οποίος στις σφιγμένες γροθιές του κρατάει πέτρες, προσπαθεί να ξεφύγει,και η Αριάδνη χειρονομεί δείχνοντας την αναστάτωσή της..
        /// </summary>
        internal static string room3_2_4_text {
            get {
                return ResourceManager.GetString("room3_2_4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_2_5 {
            get {
                object obj = ResourceManager.GetObject("room3_2_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Κόρη, γνωστή ως η «Κόρη με το ρόδι», βρέθηκε το 1887 στα ανατολικά του Ερεχθείου. Είναι ντυμένη με τρία διαδοχικά ενδύματα. Από μέσα φορά μακρύ χιτώνα, από τον οποίο είναι ορατό μόνο το δεξί μανίκι, πιασμένο με μικρά ανάγλυφα κουμπιά. Από πάνω φορά πέπλο, στολισμένο με κόκκινο μαίανδρο, σταυρούς και άστρα, δεμένο στη μέση με πράσινη ζώνη. Η ενδυμασία ολοκληρώνεται με μακρύ επίβλημα, το οποίο πέφτει συμμετρικά από τους ώμους και διακοσμείται στην παρυφή με μαίανδρο, σταυρούς και φούντες στις άκρες..
        /// </summary>
        internal static string room3_2_5_text {
            get {
                return ResourceManager.GetString("room3_2_5_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_2_6 {
            get {
                object obj = ResourceManager.GetObject("room3_2_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Έλασμα με παράσταση γοργονείου το οποίο βρέθηκε νότια του Παρθενώνα. Το πρόσωπο της Μέδουσας Γοργούς πλαισιώνουν τα μαλλιά της με δώδεκα τούφες που απολήγουν σε φίδια. Το στρογγυλό αυτό γοργόνειο πρέπει μάλλον να χρησίμευε ως επίσημα (έμβλημα) ασπίδας αν και θα μπορούσε να προέρχεται και από τη διακόσμηση ενός μεγάλου χάλκινου αγγείου.
        ///
        ///Ως θέμα συνδέεται άμεσα με την κύρια θεότητα της Ακρόπολης την Αθηνά, καθώς ο Περσέας, όταν σκότωσε τη Μέδουσα Γοργώ, χάρισε το κομμένο κεφάλι της στη θεά η οποία διακόσμη [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_2_6_text {
            get {
                return ResourceManager.GetString("room3_2_6_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η οικοδομική αναδιοργάνωση της Ακρόπολης στη διάρκεια του 6ου αι. π.Χ. και η ανάδειξή της σε τόπο πολιτικής και κοινωνικής προβολής στέκεται η αιτία να πλημμυρίσει ο χώρος από τα αφιερώματα των πιστών. Το είδος, το μέγεθος και το υλικό κατασκευής των αφιερωμάτων καθορίζονται από την οικονομική δυνατότητα, την κοινωνική θέση και την ενασχόληση του προσώπου που τα αφιερώνει. Τα πανάκριβα μαρμάρινα γλυπτά, τα δαπανηρά χάλκινα έργα και τα πολυτελή αγγεία είναι αφιερώματα αριστοκρατών ή πλούσιων βιοτεχνών, ενώ τ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_2_text {
            get {
                return ResourceManager.GetString("room3_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_3_1 {
            get {
                object obj = ResourceManager.GetObject("room3_3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το πρόσωπο είναι ωοειδές, τα μάτια μεγάλα και τα βλέφαρα έντονα. Τα μαλλιά είναι χωρισμένα στη μέση και μαζεμένα σε σάκκο. Ο λαιμός είναι ψηλός και το κάτω τμήμα του έχει διαμορφωθεί κατάλληλα για την ένθεση του κεφαλιού σε σώμα ειδωλίου ή σε βάση προτομής. Διατηρούνται ίχνη λευκού επιχρίσματος..
        /// </summary>
        internal static string room3_3_1_text {
            get {
                return ResourceManager.GetString("room3_3_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_3_2 {
            get {
                object obj = ResourceManager.GetObject("room3_3_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βρέθηκε πίσω από το Ερέχθειο, πιθανότατα γύρω στο 1882, και είναι συγκολλημένο από τρία θραύσματα.
        ///
        ///Παριστάνει την Αθηνά και έναν καθιστό άνδρα. Η θεά φοράει μακρύ χιτώνα και ιμάτιο, αιγίδα με φίδια στις άκρες και σανδάλια. Στο υψωμένο αριστερό χέρι θα κρατούσε δόρυ, ζωγραφισμένο άλλοτε στο βάθος του αναγλύφου. Ο άνδρας είναι καθισμένος σε κλισμό (καρέκλα) με γυμνό το πάνω μέρος του σώματος. Μπροστά του έχει έναν πάγκο ή τραπέζι, πάνω στον οποίο είναι ακουμπισμένο κάποιο αντικείμενο, και με το δεξί χέρι μ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_3_2_text {
            get {
                return ResourceManager.GetString("room3_3_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_3_3 {
            get {
                object obj = ResourceManager.GetObject("room3_3_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Βρέθηκε σε δύο τμήματα το 1888 στα νότια του Παρθενώνα και είναι ένα από τα σημαντικότερα έργα του ονομαζόμενου «αυστηρού ρυθμού».
        ///
        ///Εικονίζει την Αθηνά μπροστά σε μία χαμηλή στήλη. Η θεά φοράει πέπλο που σφίγγεται στη μέση με ζώνη και κράνος κορινθιακού τύπου. Με το ένα χέρι στηρίζεται στο δόρυ της και το άλλο είναι ακουμπισμένο στον γοφό. Τα πόδια της είναι γυμνά. Το βάρος του σώματος πέφτει στο δεξί πόδι ενώ το αριστερό, λυγισμένο προς τα πίσω, μόλις που πατά με τα δάχτυλα στο έδαφος. Έχει το κεφάλι σκυ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_3_3_text {
            get {
                return ResourceManager.GetString("room3_3_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_3_4 {
            get {
                object obj = ResourceManager.GetObject("room3_3_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το κεφάλι προέρχεται από άγαλμα εφήβου, πιθανώς αθλητή. Βρέθηκε το 1887 στην περιοχή του ιερού του Πανδίονα, στη διάρκεια αρχαιολογικών ανασκαφών για την κατασκευή του παλαιού Μουσείου της Ακρόπολης. Η σύγχρονη ονομασία «ξανθός έφηβος» οφείλεται στα υπολείμματα χρυσοκίτρινου χρώματος που διατηρούσε στα μαλλιά όταν βρέθηκε. Επίσης διατηρούσε ίχνη κόκκινου χρώματος στα χείλη και κιτρινωπού στα μάτια..
        /// </summary>
        internal static string room3_3_4_text {
            get {
                return ResourceManager.GetString("room3_3_4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_3_5 {
            get {
                object obj = ResourceManager.GetObject("room3_3_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κεφάλι αγάλματος σχεδόν φυσικού μεγέθους. Βρέθηκε το 1886 στα βορειοανατολικά των Προπυλαίων.
        ///
        ///Εικονίζει γενειοφόρο οπλίτη με φυσιοκρατικά χαρακτηριστικά. Το πάνω και πίσω μέρος του κεφαλιού είναι λείο και φέρει οπές και μικρά στελέχη για τη στερέωση πρόσθετου κράνους. Τα μαλλιά στο μέτωπο σχηματίζουν κοντές μπούκλες, το γένι δηλώνεται με κυματιστές εγχαράξεις και τα φρύδια αποδίδονται ανάγλυφα. Ο σκληρός χιτώνας των ματιών είναι κατασκευασμένος από υαλώδες υλικό ενώ η ίριδα των ματιών έχει χαθεί..
        /// </summary>
        internal static string room3_3_5_text {
            get {
                return ResourceManager.GetString("room3_3_5_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room3_3_6 {
            get {
                object obj = ResourceManager.GetObject("room3_3_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Κεφάλι από άγαλμα μικρού μεγέθους. Βρέθηκε το 1866 στη διάρκεια εργασιών για τη θεμελίωση του παλαιού Μουσείου, της Ακρόπολης.
        ///
        ///Παριστάνεται αγένειος νέος, πιθανότατα αθλητής. Έχει μακριά μαλλιά που τυλίγονται γύρω από δακτύλιο και αναδιπλώνονται πίσω σχηματίζοντας χαλαρό κότσο. Ο σκληρός χιτώνας των ματιών είναι κατασκευασμένος από υαλώδες υλικό ενώ η ίριδα των ματιών έχει χαθεί. Θεωρείται έργο του ονομαζόμενου «αυστηρού ρυθμού»..
        /// </summary>
        internal static string room3_3_6_text {
            get {
                return ResourceManager.GetString("room3_3_6_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η εμπειρία των Περσικών Πολέμων φέρνει αλλαγές στην κοινωνία, τη σκέψη και την τέχνη της Αθήνας. Μετά το 480 π.Χ. οι καλλιτέχνες αναζητούν νέους τρόπους έκφρασης, ικανούς να αποδώσουν το ηρωικό πνεύμα που επικρατεί. Τα νέα έργα απεικονίζουν όχι μόνο θεούς αλλά και θνητούς, ιδιαίτερα αθλητές.
        ///
        ///Οι γλύπτες μελετούν τη γλώσσα του σώματος και προσπαθούν να αναδείξουν τον εσωτερικό κόσμο του ανθρώπου. Στον άκαμπτο κορμό των αρχαϊκών αγαλμάτων αντιπαραθέτουν μια πιο φυσιοκρατική στάση. Μετατοπίζουν το βάρος του  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room3_3_text {
            get {
                return ResourceManager.GetString("room3_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream room3_sound {
            get {
                return ResourceManager.GetStream("room3_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Στη δυτική πλευρά του πρώτου ορόφου παρουσιάζονται έργα από τα άλλα μνημεία του οικοδομικού προγράμματος του Περικλή, ορισμένα από τα οποία ολοκληρώνονται μετά τον θάνατό του. Η έκθεση περιλαμβάνει γλυπτά και αρχιτεκτονικά μέλη από τα Προπύλαια, τον ναό της Αθηνάς Νίκης και το Ερέχθειο..
        /// </summary>
        internal static string room4 {
            get {
                return ResourceManager.GetString("room4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room4_1_1 {
            get {
                object obj = ResourceManager.GetObject("room4_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τα Προπύλαια, η μνημειακή είσοδος στο ιερό της Ακρόπολης, χτίζονται μεταξύ του 437 και του 431 π.Χ., σε σχέδια του Μνησικλή, στη θέση αρχαιότερης πύλης. Το αρχικό σχέδιο δεν ολοκληρώνεται ποτέ, καθώς η κατασκευή σταματά τις παραμονές του Πελοποννησιακού Πολέμου, το 431 π.Χ.
        ///
        ///Το οικοδόμημα αποτελείται από μία κεντρική είσοδο και δύο πλευρικές πτέρυγες. Την κεντρική είσοδο πλαισιώνουν τρία ζεύγη κιόνων ιωνικού ρυθμού, με εξαιρετικής τέχνης κιονόκρανα. Η είσοδος διαθέτει πέντε θύρες, η μεσαία από τις οποίες  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room4_1_text {
            get {
                return ResourceManager.GetString("room4_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room4_2_1 {
            get {
                object obj = ResourceManager.GetObject("room4_2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ο ναός της Αθηνάς Νίκης κατασκευάζεται ανάμεσα στο 426 και το 421 π.Χ. πάνω στον πύργο της νοτιοδυτικής άκρης της Ακρόπολης, σύμφωνα με τα σχέδια του αρχιτέκτονα Καλλικράτη. Αντικαθιστά αρχαιότερους ναούς που τα κατάλοιπά τους διατηρούνται στο εσωτερικό του πύργου.
        ///
        ///Ο ναός είναι ιωνικού ρυθμού και έχει ανάγλυφη ζωφόρο με διαφορετικές παραστάσεις σε κάθε πλευρά. Στην ανατολική εικονίζεται σύναξη θεών γύρω από τον ένθρονο Δία, ενώ στις άλλες αναπτύσσονται σκηνές μάχης Ελλήνων με Πέρσες και Ελλήνων με άλλους [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room4_2_text {
            get {
                return ResourceManager.GetString("room4_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap room4_3_1 {
            get {
                object obj = ResourceManager.GetObject("room4_3_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το Ερέχθειο είναι ένα σύνθετο οικοδόμημα, που κατασκευάζεται την τελευταία εικοσαετία του 5ου αι. π.Χ. σε σχέδια του Μνησικλή. Αντικαθιστά στη λειτουργία του τον Αρχαίο Ναό της Αθηνάς Πολιάδας, τμήμα του οποίου είχαν καταστρέψει οι Πέρσες εξήντα χρόνια νωρίτερα. Το νέο κτήριο χωρίζεται σε δύο μέρη. Το ανατολικό είναι αφιερωμένο στην Αθηνά και στεγάζει το ξύλινο λατρευτικό της άγαλμα, ενώ το δυτικό, που είναι χαμηλότερο, είναι αφιερωμένο στη λατρεία του Ποσειδώνα-Ερεχθέα, του Ηφαίστου και του Βούτη, αδελφού  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string room4_3_text {
            get {
                return ResourceManager.GetString("room4_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_object_1 {
            get {
                object obj = ResourceManager.GetObject("rsz_object_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_object_2 {
            get {
                object obj = ResourceManager.GetObject("rsz_object_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_object_3 {
            get {
                object obj = ResourceManager.GetObject("rsz_object_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_object_4 {
            get {
                object obj = ResourceManager.GetObject("rsz_object_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_object_5 {
            get {
                object obj = ResourceManager.GetObject("rsz_object_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rsz_room2_1_1 {
            get {
                object obj = ResourceManager.GetObject("rsz_room2_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small_1 {
            get {
                object obj = ResourceManager.GetObject("small_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αίθουσα των κλιτύων της Ακρόπολης.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η Ακρόπολη στις αρχές της ιστορίας της.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η αίθουσα της αρχαϊκής Ακρόπολης.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Τα άλλα μνημεία του προγράμματος του Περικλή.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap αιθ2_1 {
            get {
                object obj = ResourceManager.GetObject("αιθ2_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap αιθ2_2 {
            get {
                object obj = ResourceManager.GetObject("αιθ2_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap αιθ2_3 {
            get {
                object obj = ResourceManager.GetObject("αιθ2_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap αιθουσα1_1 {
            get {
                object obj = ResourceManager.GetObject("αιθουσα1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap αιθουσα1_2 {
            get {
                object obj = ResourceManager.GetObject("αιθουσα1_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap αιθουσα1_3 {
            get {
                object obj = ResourceManager.GetObject("αιθουσα1_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Η ακόλουθη εφαρμογή αποσκοπεί στην παρουσίαση του Μουσείου της Ακρόπολης. Απευθύνεται σε όλες τις ηλικίες καθώς υλοποιήθηκε με τέτοιο τρόπο, ώστε ο μέσος χρήστης να βρίσκεται σε θέση να τη χρησιμοποιήσει χωρίς να διαθέτει κάποιο γνωσιακό υπόβαθρο στη χρήση ηλεκτρονικών υπολογιστών.
        ///Στο αρχικό μενού υπάρχει η επιλογή &quot;Εκκίνηση&quot;. Εάν ο χρήστης πατήσει αυτό το κουμπί τότε ξεκινάει η ψηφιακή περιήγηση στο Μουσείο της Ακρόπολης.Στην οθόνη θα εμφανίζονται διάφορες εικόνες από τoυς εκθεσιακούς χώρους του μουσείου [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Εισαγωγικό_σημείωμα {
            get {
                return ResourceManager.GetString("Εισαγωγικό σημείωμα", resourceCulture);
            }
        }
    }
}
